name: dart_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  dart_jsonwebtoken: ^2.7.1
  crypto: ^3.0.3
  uuid: ^3.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
